---
title: "RWorksheet_salve#3aPDF"
author: "Ben Robert T. Salve."
date: "2022-10-24"
output: pdf_document
---

# Ben Robert T. Salve. BSIT2-A
# Worksheet3

## 1)
```{r}
LETTERS
letters
```

## a. 
```{r}
x <- LETTERS
x [1:11]
```

## b.
```{r}
odd_letters <- LETTERS
odd_letters

odd_letters <- LETTERS[1:26 %% 2 !=0]
odd_letters
```

## c.
```{r}
vowel_letters <- LETTERS[c(1, 5, 9, 15, 21)]
vowel_letters
```


## d.
```{r}
last_5ll <- letters
last_5ll [22:26]
```

## e.
```{r}
letters_between <- letters
letters_between [15:24]
```

## 2)

## a. 
## R code:
```{r}
city <- c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City")
city
```

## b.
```{r}
temp <- c(42, 39, 34, 34, 30, 27)
temp
```

## c. 
```{r}
names(temp) <- city
temp
```
#The result of the code is, it set a name for the object temp. 

## d.
## Rcode:
```{r}
temp[c(5, 6)]
```
#The content of index 5 and 6 are:
#Samal Island   Davao City 
#30             27 



# Using Matrices 
## 2)

## a. 
## R code:
```{r}
mat1 <- matrix(c(1:8, 11:14), 3, 4)
mat1
```

## b. 
## R code:
```{r}
mat1*2
```

## c. 
## R code:
```{r}
mat1[2,]
```

## d. 
## R code:
```{r}
mat1 [c(1,2),c(3,4)]
```

## e. 
## R code:
```{r}
mat1 [c(3),c(2,3)]
```

## f.
## R code:
```{r}
mat1 [,4]
```

## g. 
## R code:
```{r}
dimnames(mat1) <- list(c("isa", "dalawa", "tatlo"),c("uno", "dos", "tres", "quatro"))
mat1
```

## h. 
## R code:
```{r}
dim(mat1) <- c(6,2)
mat1
```

# Using arrays
## 3. 
## a. 
## R code:
```{r}
a1 <- array(c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1))
a1

v1 <- array(rep(a1, 2), dim = c(2,4,3))
v1
```

## b. 
## R code:
```{r}
dim(v1)
```
#We have 3 dimensions. 

## c. 
## R code:
```{r}
dimnames(v1) <- list(letters[1:2], LETTERS[1:4], c("1st-Dimensional Array", "2nd-Dimentional Array", "3rd-Dimensional Array"))
v1
```

